SPEAR:
  ENGINE_SERVICE:
    PRINT_CALL_DEBUG_INFO: false
  ENVIRONMENT_VARS: {}
  INSTANCE:
    CLIENT_FORCE_RETURN_ALIGNED_ARRAYS: false
    CLIENT_INTERNAL_TIMEOUT_SECONDS: 2.0
    CLIENT_VERBOSE_ALLOCATIONS: false
    CLIENT_VERBOSE_EXCEPTIONS: true
    CLIENT_VERBOSE_RPC_CALLS: false
    COMMAND_LINE_ARGS:
      fullstdoutlogoutput: null
      nologtimes: null
      nosound: null
      resx: 512
      resy: 512
      stdout: null
      windowed: null
    EDITOR_CLIENT_INTERNAL_RECONNECT_LIMIT: 1
    EDITOR_EXECUTABLE: ''
    EDITOR_LAUNCH_MODE: ''
    EDITOR_UPROJECT: ''
    GAME_EXECUTABLE: ''
    GET_EDITOR_WAIT_FOR_ENGINE_IDLE:
      MAX_TIME_SECONDS: 1000.0
      SLEEP_TIME_SECONDS: 1.0
    GET_EDITOR_WAIT_FOR_WORLD_INITIALIZED:
      MAX_TIME_SECONDS: 5.0
      SLEEP_TIME_SECONDS: 1.0
    GET_EDITOR_WARM_UP:
      NUM_FRAMES: 1
      TIME_SECONDS: 5.0
    GET_GAME_WAIT_FOR_ENGINE_IDLE:
      MAX_TIME_SECONDS: 1000.0
      SLEEP_TIME_SECONDS: 1.0
    GET_GAME_WAIT_FOR_WORLD_INITIALIZED:
      MAX_TIME_SECONDS: 5.0
      SLEEP_TIME_SECONDS: 1.0
    GET_GAME_WARM_UP:
      NUM_FRAMES: 1
      TIME_SECONDS: 5.0
    INITIALIZE_CLIENT_MAX_TIME_SECONDS: 120.0
    INITIALIZE_CLIENT_SLEEP_TIME_SECONDS: 1.0
    INITIALIZE_WAIT_FOR_WORLD_INITIALIZED:
      MAX_TIME_SECONDS: 5.0
      SLEEP_TIME_SECONDS: 1.0
    INITIALIZE_WARM_UP:
      NUM_FRAMES: 1
      TIME_SECONDS: 5.0
    REQUEST_EXIT_UNREAL_INSTANCE_SLEEP_TIME_SECONDS: 1.0
    TEMP_CONFIG_FILE: config.yaml
    TEMP_DIR: tmp
  LAUNCH_MODE: none
  UNREAL_OBJECT:
    PRINT_CALL_DEBUG_INFO: false
SP_CORE:
  EDITOR_INI_CONFIG_VALUES: {}
  ENGINE_INI_CONFIG_VALUES: {}
  GAME_INI_CONFIG_VALUES: {}
  GAME_USER_SETTINGS_INI_CONFIG_VALUES: {}
  INPUT_INI_CONFIG_VALUES: {}
  MESH_PROXY_COMPONENT_MANAGER:
    VERBOSE: false
  PROXY_COMPONENT_MANAGER:
    VERBOSE: false
  SHARED_MEMORY_INITIAL_UNIQUE_ID: 4832359
  WAIT_FOR_KEYBOARD_INPUT_DURING_INITIALIZATION: false
SP_SERVICES:
  ENGINE_SERVICE:
    DOUBLE_BUFFERED_WORK_QUEUES: false
    PRINT_CALL_DEBUG_INFO: false
    PRINT_FRAME_DEBUG_INFO: false
    STEPPING_MODE: async
    STEPPING_UE_TICKS_PER_ENV_STEP: 1
  ENHANCED_INPUT_SERVICE:
    PRINT_INJECT_DEBUG_INFO: false
  INITIALIZE_ENGINE_SERVICE:
    BENCHMARKING: true
    EDITOR_STARTUP_MAP: ''
    FIXED_DELTA_TIME: 0.03333333333333333
    GAME_DEFAULT_MAP: ''
    GLOBAL_DEFAULT_GAME_MODE: ''
    MOUNT_PAK_FILES: false
    NAVIGATION_SYSTEM_DEFAULT_OBJECT_STRING: '''{}'''
    OVERRIDE_BENCHMARKING: true
    OVERRIDE_EDITOR_STARTUP_MAP: false
    OVERRIDE_FIXED_DELTA_TIME: true
    OVERRIDE_GAME_DEFAULT_MAP: false
    OVERRIDE_GLOBAL_DEFAULT_GAME_MODE: false
    OVERRIDE_NAVIGATION_SYSTEM_DEFAULT_OBJECT: false
    OVERRIDE_PHYSICS_SETTINGS: false
    OVERRIDE_RECAST_NAV_MESH_DEFAULT_OBJECT: false
    PAK_FILES: []
    PHYSICS_SETTINGS_STRING: '''{}'''
    RECAST_NAV_MESH_DEFAULT_OBJECT_STRING: '''{}'''
  INPUT_SERVICE:
    PRINT_INJECT_DEBUG_INFO: false
  RPC_SERVICE:
    RPC_BIND_RETRY_COUNT: 3
    RPC_BIND_RETRY_DELAY_SEC: 0.25
    RPC_SERVER_PORT: 47834
    SKIP_ON_NET_CLIENT: true
  SKIP_ON_CLIENT_BUILD: true
  WORK_QUEUE:
    PRINT_CALL_DEBUG_INFO: false
  WORLD_REGISTRY_SERVICE:
    FORCE_SKYLIGHT_UPDATE: true
    FORCE_SKYLIGHT_UPDATE_MAX_DURATION_SECONDS: 1.0
    GAME_PAUSED: true
    OVERRIDE_GAME_PAUSED: false
    SPAWN_SP_STABLE_NAME_MANAGER: true
